const ReportFeedbackActions = {
  GET_ALL_REPORTED_FEEDBACKS: "GET_ALL_REPORTED_FEEDBACKS",
  GET_ALL_REPORTED_FEEDBACKS_SUCCESS: "GET_ALL_REPORTED_FEEDBACKS_SUCCESS",
  GET_REPORTS_BY_FEEDBACK_ID: "GET_REPORTS_BY_FEEDBACK_ID",
  GET_REPORTS_BY_FEEDBACK_ID_SUCCESS: "GET_REPORTS_BY_FEEDBACK_ID_SUCCESS",
  UPDATE_REPORT_STATUS: "UPDATE_REPORT_STATUS",
  UPDATE_REPORT_STATUS_SUCCESS: "UPDATE_REPORT_STATUS_SUCCESS",
};

export default ReportFeedbackActions;